feature/update-time-service: add time difference to time service
eska-global/common pull request #11
Opened 2019-09-25 15:18 UTC by TetianaSatsuk

2019-09-25 15:24 UTC, macaqueee commented on src/time_service/index.ts
> +        this.init();
you are calling async function here. so constructor will return Promise, not instance.

2019-09-25 15:25 UTC, macaqueee commented on src/time_service/index.ts
> +    getTimeFromServer(date: Date): Promise<number>;
is it correct signature?

2019-09-26 08:23 UTC, macaqueee approved these changes

2019-09-27 07:17 UTC, Verbalist requested changes

2019-09-27 07:17 UTC, Verbalist commented on src/time_service/index.ts
> +        this.getTimeFromServer().then((networkTime: number) => {
перепиши в async стиле

2019-09-27 07:17 UTC, Verbalist commented on src/time_service/index.ts
> +    getTime();
: number

2019-09-27 08:23 UTC, macaqueee commented on src/time_service/config.ts
> +        this.PROTOCOL = process.env.protocol || 'http';
lets rename to `TIME_SERVER_PROTOCOL`

2019-09-27 08:23 UTC, macaqueee commented on src/time_service/config.ts
> +        this.HOST = process.env.host || '0.0.0.0';
lets rename to `TIME_SERVER_HOST`

2019-09-27 08:28 UTC, Verbalist approved these changes

2019-09-27 08:49 UTC, merged